spring:
  application:
    name: rocketmq-producer
rocketmq:
  name-server: 192.168.84.134:9876  # rocketMq的nameServer地址
  producer:
    group: producer-group  # 生产者组别
    send-message-timeout: 3000  # 消息发送的超时时间 默认3000ms
    max-message-size: 4194304       # 消息的最大长度 默认为128K
    #消息达到4096字节的时候，消息就会被压缩。默认 4096
    compress-message-body-threshold: 4096
    #同步消息发送失败重试次数
    retry-times-when-send-failed: 3
    #在内部发送失败时是否重试其他代理，这个参数在有多个broker时才生效
    retry-next-server: true
    #异步消息发送失败重试的次数
    retry-times-when-send-async-failed: 3