spring:
  application:
    name: rocketmq-producer
rocketmq:
  name-server: 192.168.84.134:9876  # rocketMq的nameServer地址
  producer:
    group: producer-group  # 生产者组别
    send-message-timeout: 3000  # 消息发送的超时时间
    retry-times-when-send-failed: 2  # 异步消息发送失败重试次数
    max-message-size: 4194304       # 消息的最大长度
    enable-msg-trace: true