spring:
  # \u914D\u7F6E\u6570\u636E\u6E90\u4FE1\u606F
  datasource:
    # \u914D\u7F6E\u6570\u636E\u6E90\u7C7B\u578B
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # \u914D\u7F6E\u8FDE\u63A5\u6570\u636E\u5E93\u4FE1\u606F
      url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123123
# \u914D\u7F6EMyBatis-plus
mybatis-plus:
  type-aliases-package: com.hjc.demo.pojo
  # \u914D\u7F6EMyBatis-plus\u65E5\u5FD7
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
