server:
  port: 8301
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # 应用名称 borrow-service
    name: borrow-service
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        # 用户名
        username: nacos
        # 密码
        password: nacos
        # 开启注册与发现
        enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
      compression:
        request:
          enabled: true  # 请求压缩
          mime-types: [ "text/xml", "application/xml", "application/json" ]  # 压缩的类型
          min-request-size: 1024  # 请求最小压缩的阈值
        response:
          enabled: true  # 响应压缩
      client:
        config:
          default:
            # 连接超时: consumer连接上provider的时间阈值，起决定作用的是网络状况
            connect-timeout: 5000 #防止由于服务器处理时间长而阻塞调用者 单位：毫秒
            # 读超时: consumer发出请求到接收到provider响应的时间阈值，其决定作用的是provider的业务逻辑
            read-timeout: 5000 #从连接建立时开始应用，在返回响应时间过长时触发 单位：毫秒
          book-service:
            connect-timeout: 3000 #防止由于服务器处理时间长而阻塞调用者
            read-timeout: 3000 #从连接建立时开始应用，在返回响应时间过长时触发
      #  Apache HttpClient5 配置开启
      httpclient:
        hc5:
          enabled: true
logging:
  level:
    com.hjc: debug