server:
  port: 8301
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver