server:
  port: 8201
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # 应用名称 book-service
    name: book-service
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
#        server-addr: 192.168.0.111:8850,192.168.0.111:8852,192.168.0.111:8854
#        server-addr: 192.168.56.182:8850,192.168.56.182:8852,192.168.56.182:8854
        # 用户名
        username: nacos
        # 密码
        password: nacos
        # 修改为上海地区的集群
        cluster-name: Shanghai
