spring:
  mvc:
    contentnegotiation:
      # 开启基于请求参数的内容协商功能。 默认参数名：format。 默认此功能不开启
      favor-parameter: true
      # 指定内容协商时使用的参数名。默认是 format
      parameter-name: type
      # 新增一种媒体类型
      media-types:
        yaml: text/yaml
