pipeline {
    agent any

    stages {
        stage('test拉取代码') {
            steps {
                echo '拉取代码完成'

            }

        }
        stage('执行构建') {
            steps {
                echo '执行构建完成'

            }

        }
    }

    post {

        always {

            echo "完成"

        }

        failure {

            echo "失败"
        }
    }
}